name: teknigo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  
  cupertino_icons: ^1.0.8
  sign_in_with_apple: ^7.0.1

  # Para Google Maps y ubicación
  google_maps_flutter: ^2.5.3
  location: ^8.0.0
  geocoding: ^3.0.0

  # Para manejo de imágenes
  image_picker: ^1.0.6
  path_provider: ^2.1.2
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  firebase_app_check: ^0.3.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
