// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjWENQnLh7R0iYI8_h13w2YbSBuK6ggIM',
    appId: '1:986469489948:web:53dbdcad634c37575aeed9',
    messagingSenderId: '986469489948',
    projectId: 'teknigo-6e905',
    authDomain: 'teknigo-6e905.firebaseapp.com',
    storageBucket: 'teknigo-6e905.firebasestorage.app',
    measurementId: 'G-FGCCWF9N8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jyzkQlMIPNmDXw5nEbOZeOmEx9-fg00',
    appId: '1:986469489948:android:2c0fc9745a0b5c7f5aeed9',
    messagingSenderId: '986469489948',
    projectId: 'teknigo-6e905',
    storageBucket: 'teknigo-6e905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfhQ2675OrIH0mcaxZmVjMcWXgWpmXB0k',
    appId: '1:986469489948:ios:639dcf832c7f9ff75aeed9',
    messagingSenderId: '986469489948',
    projectId: 'teknigo-6e905',
    storageBucket: 'teknigo-6e905.firebasestorage.app',
    iosClientId: '986469489948-36ib97su28oitd4pdj0nnds77eld2r6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.teknigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfhQ2675OrIH0mcaxZmVjMcWXgWpmXB0k',
    appId: '1:986469489948:ios:639dcf832c7f9ff75aeed9',
    messagingSenderId: '986469489948',
    projectId: 'teknigo-6e905',
    storageBucket: 'teknigo-6e905.firebasestorage.app',
    iosClientId: '986469489948-36ib97su28oitd4pdj0nnds77eld2r6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.teknigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjWENQnLh7R0iYI8_h13w2YbSBuK6ggIM',
    appId: '1:986469489948:web:fc870f14da9ea76a5aeed9',
    messagingSenderId: '986469489948',
    projectId: 'teknigo-6e905',
    authDomain: 'teknigo-6e905.firebaseapp.com',
    storageBucket: 'teknigo-6e905.firebasestorage.app',
    measurementId: 'G-16ZF1T0ZKD',
  );
}
